services:
  smokey:
    container_name: mywebsite
    image: drake/smoker
    volumes:
      - type: bind
        source: /root/website/caddy
        target: /data
    ports:
      - 443:443
    networks:
      - website
networks:
  website:
    name: website
    driver: bridge
